### PR TITLE
Support for chocolatey

### PR DESCRIPTION
**Pull request by chevdor**
Hi Ruben,

Quick PR including chocolatey support.
It is a quick version to get started. It can be improved. In the current version it first requires chocolatey to be installed (see chocolatey.org). If this is not the case, the **cpack** command will fail.
I already added nuget as dependency as I think we can also use nuget directly to build the package. This would remove the requirement to have chocolatey installed on the system to build the package.

### CODE REVIEW

**Comment by chevdor** [comment]
And here you go with the conflicts resolved.

**Comment by cyclops1982** [comment]
Sorry:

Error	4	The command "REM xcopy /R /Y "C:\build_git\K2NEServiceBroker\K2Field.K2NE.ServiceBroker\bin\Debug\K2Field.K2NE.ServiceBroker.dll" "c:\Program Files (x86)\K2 blackpearl\ServiceBroker\"
xcopy /R /Y "C:\build_git\K2NEServiceBroker\K2Field.K2NE.ServiceBroker\bin\Debug\K2Field.K2NE.ServiceBroker.dll" "C:\build_git\K2NEServiceBroker\\chocoPackage\tools\"
cd "C:\build_git\K2NEServiceBroker\\chocoPackage\"
cpack" exited with code 9009.	K2Field.K2NE.ServiceBroker

**Comment by chevdor** [comment]
Can you try running the cpack command manually in the chocoPackage folder ?
If that fails, we can do a short remote session in about 2 hours. This is probably no big issue.

If you just installed chocolatey by the way, you may want to reboot or at least restart your shell to ensure that the env variables are up to date.

**Comment by cyclops1982** [comment]
C:\build_git\K2NEServiceBroker\chocoPackage [chevdor-master +2 ~0 -0 !]> cpack
cpack : The term 'cpack' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ cpack
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (cpack:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

C:\build_git\K2NEServiceBroker\chocoPackage [chevdor-master +2 ~0 -0 !]>
C:\build_git\K2NEServiceBroker\chocoPackage [chevdor-master +2 ~0 -0 !]>
C:\build_git\K2NEServiceBroker\chocoPackage [chevdor-master +2 ~0 -0 !]> cd .\tools
C:\build_git\K2NEServiceBroker\chocoPackage\tools [chevdor-master +2 ~0 -0 !]> cpack
cpack : The term 'cpack' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ cpack
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (cpack:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException




I haven't installed chocoPackage? I think VS does that by itself?

**Comment by cyclops1982** [comment]
cinst K2NEServiceBroker doesn't work for me!

**Comment by chevdor** [comment]
If you need help, you´ll have to tell me more!
cinst runs powershell scripts in the back. So either you see some kind of failure and we can figure out the issue from there (such as not being admin, ...)

If not, it is also possible to run the ps script 'by hand'.
The scripts that failed can be found:
* in the recent versions: in %PROGRAMDATA%\chocolatey\lib-bad
* in earlier versions in c:\chocolatey\lib-bad

In here you can run the script and debug it to see if there is something wrong in the script itself.

**Comment by cyclops1982** [comment]
Well, can you check out the branch and see if it works on your end?

**Comment by chevdor** [comment]
I tested the package before the PR so I am sure it works on my side.
I tested again:
````
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\...>cinst K2NEServiceBroker
Chocolatey (v0.9.8.23) is installing 'K2NEServiceBroker' and dependencies. By in
stalling you accept the license for 'K2NEServiceBroker' and each dependency you
are installing.
______ K2NEServiceBroker v0.0.1.1 ______
Stopping Service
Stopping K2 blackpearl service on localhost
Installing files
Starting Service
Starting K2 blackpearl service on localhost
WARNING: Waiting for service 'K2 blackpearl Server (K2 blackpearl Server)' to
start...
Finished installing 'K2NEServiceBroker' and dependencies - if errors not shown i
n console, none detected. Check log for errors if unsure.
Reading environment variables from registry. Please wait... Done.
````

As you see it works fine. So to understand what is wrong on your side, we would need your output.

**Pull request merged**
